### ISSUE TITLE
[01-01] 카프카를 활용한 데이터 파이프라인 구축

### ISSUE THREAD

**Issue by snaag** [dev-writeup-2024/january#2]
# 카프카를 활용한 데이터 파이프라인 구축

### 데이터 파이프라인이란
  - 다양한 데이터 소스에서 원시 데이터를 수집한 다음 분석을 위해 데이터 레이크 또는 데이터 웨어하우스와 같은 데이터 저장소로 이전하는 것 
  - 즉 수집하고 이동하고 적재하는 것
### 데이터 파이프라인의 구성 요소
  - `Apache` NiFi
    - 데이터 흐름을 정의하고, 정의된 흐름대로 자동으로 실행해주는 애플리케이션
  - `Elastic` Filebeat
    - 로그 데이터를 수집하고, 이를 ES 나 Logstash 같은 중앙집중식 데이터 저장소로 전송하는 것
  - `Elastic` ElasticSearch
    - 분산 검색 및 분석 엔진으로, JSON 문서를 저장, 검색 및 분석할 수 있음 
    - Elasticsearch는 높은 확장성과 신속한 검색 기능으로 유명하며, 대규모 데이터 집합을 다룰 때 매우 효율적임
  - `Elastic` Kibana
    - Elasticsearch에 저장된 데이터를 시각화하고 탐색하는 웹 기반 인터페이스
    - 대시보드 생성, 시각화 도구, 지리적 데이터 매핑 등 다양한 기능을 제공
  - 엘라스틱 스택 (Elastic Stack) 이란 
    - 데이터 분석에 필요한 모든 유형의 데이터를 실시간으로 검색, 분석 및 시각화할 수 있는 *Elastic* 사의 오픈소스 데이터 분석 플랫폼
    - 파일비트, 엘라스틱서치, 키바나 등이 포함되어있음

## NiFi vs Airflow

- 목적
  - NiFi: **데이터** 흐름과 처리가 목적 
  - Airflow: 작업 흐름(워크플로우)의 스케줄링 및 모니터링이 목적
- 설계 (?) 방법
  - NiFi: UI 를 통해 사용
  - Airflow: **워크플로우** 의 정의를 Python 코드로 작성, 확인은 UI 로 가능 
- 사용 예시 
  - NiFi: 데이터 수집 및 분산, IoT(사물인터넷) 데이터 처리, 실시간 데이터 피드 처리 등
  - Airflow: 배치 데이터 처리, ETL 작업(Extract, Transform, Load), 데이터 파이프라인 구축 및 관리 등
- 정리
  - 같이 사용할 수는 있으나 대체는 어려움 

## 카프카를 활용한 데이터 흐름도 

- 큰 구조 
  - 프로듀서: 메시지를 생산해낸 다음 그 메시지를 카프카로 전송하는 것
  - 카프카: 프로듀서가 생산한 메시지를 저장하는 중간 큐 
  - 컨슈머: 카프카에 저장된 메시지를 가져오는 역할
- 예시
  1. 카프카에서 생성되는 로그를 Filebeat 로 수집
  2. 이를 NiFi 를 통해 Kfakfa 의 큐 로부터 가져옴 
  3. ES 에 저장함
  4. Kibana 를 사용하여 ES 에 저장된 데이터 확인 

## [프로듀서] 파일비트를 이용한 메시지 전송 

- 카프카의 로그를 카프카의 토픽으로 전송하려면 프로듀서가 필요함
- 프로듀서
  - **Filebeat**, 카프카 클라이언트 라이브러리, 등...
- 파일비트 설정 파일 
```yml
#====== (1) Filebeat prospectors
kafka.home: /usr/local/kafka
filebeat.prospectors: # Filebeat가 로그 파일을 수집할 위치와 방법을 정의
- input_type: log # 로그 파일을 읽음 
    paths: # Filebeat가 수집할 로그 파일의 위치를 지정
      - ${kafka.home}/logs/server.log*
  multiline.pattern: '^\['
  multiline.negate: true
  multiline.match: after
  # Filebeat가 로그 파일에서 multiline 로그를 어떻게 처리할지 정의
  fields.pipeline: kafka-logs
  # 추가적인 메타데이터를 로그 데이터에 추가하는 데 사용
  # 로그 데이터를 처리하거나 분석할 때 사용 위함 

...

#====== (2) KAFKA output
output.kafka: # Kafka 클러스터의 브로커 주소 목록
  hosts: ["peter-kafka001:9092", "peter-kafka002:9092", "peter-kafka003:9092"]
  topic: 'peter-log' # peter-log 토픽으로 데이터 전송 
  partition.round_robin: # Kafka 토픽의 파티션에 메시지를 전송하는 방식을 정의
    reachable_only: false # 연결 가능한 모든 파티션에 라운드 로빈 방식으로 메시지를 분산시키도록  함
  required_acks: 1
  # 메시지 전송에 대한 확인 수준을 지정
  # 1은 리더 파티션으로부터 최소한 한 개의 확인이 필요함을 의미
  compression: gzip
  # Kafka로 전송되는 메시지의 압축 방식
  max_message_bytes: 1000000 
  # Kafka로 전송될 수 있는 최대 메시지 크기 
  # 바이트 단위로 지정, 예시는 1,000,000 바이트(약 1MB)
```

## [컨슈머] NiFi 를 이용해 메시지 가져오기 

- Kfaka 와 NiFi
  - NiFi는 데이터를 수집, 변환, 라우팅하는 데 사용됨
  - NiFi는 프로듀서 외에도 컨슈머로도 사용할 수 있음 
- 설정 파일

```properties
nifi.web.http.host=
-> nifi.web.http.host=peter-kafka001 또는 IP 주소 (로컬 호스트 정보)
# NiFi 웹 서버가 바인딩할 호스트 이름 또는 IP 주소 의미 
# 예를 들어 nifi.web.http.host=peter-kafka001는 NiFi 웹 인터페이스가 peter-kafka001 호스트에서 사용할 수 있다는 뜻임 

nifi.cluster.is.node=false
-> nifi.cluster.is.node=true
# 현재 NiFi 인스턴스가 클러스터의 일부인지 여부를 의미 
# 예를 들어 nifi.cluster.is.node=true는, 이 NiFi 인스턴스는 클러스터 모드로 동작하며 다른 NiFi 노드들과 통신할 수 있다는 뜻임

nifi.cluster.node.address=
-> nifi.cluster.node.address=peter-kafka001 또는 IP 주소 (로컬 호스트 정보)
# 클러스터 모드에서 이 NiFi 노드의 호스트 이름 또는 IP 주소를 지정
# 예를 들어 nifi.cluster.node.address=peter-kafka001는, 이 노드의 주소가 peter-kafka001임을 나타냄
# 이 주소는 클러스터 내 다른 노드가 이 노드와 통신하는 데 사용됨 

nifi.cluster.node.protocol.port=
-> nifi.cluster.node.protocol.port=8082
# 클러스터 통신을 위한 NiFi 노드의 프로토콜 포트를 의미
# 예를 들어 nifi.cluster.node.protocol.port=8082는 클러스터 통신을 위해 포트 8082를 사용함을 의미

nifi.zookeeper.connect.string=
-> nifi.zookeeper.connect.string=peter-zk001:2181,peter-zk002:2181,peter-zk003:2181 또는 주키퍼의 IP 주소 
# NiFi 클러스터는 상태 관리와 조정을 위해 Apache ZooKeeper를 사용함
# 이 설정은 NiFi가 연결할 ZooKeeper 서버들의 주소 목록을 지정함
# 예를 들어 nifi.zookeeper.connect.string=peter-zk001:2181,peter-zk002:2181,peter-zk003:2181는 ZooKeeper 클러스터의 세 노드에 대한 주소를 나타냄 
```

## [컨슈머] 실시간 분석을 위해 엘라스틱서치에 메시지 저장 

- ElasticSearch
  - Elastic 사의 분산형 RESTful 검색 및 분석 엔진
  - 전문 검색 질의를 이용해 원하는 데이터 분석을 빠르게 할 수 있는 애플리케이션
- 저장소 등록 파일 (elasticsearch.repo)

```repo
[elasticsearch-6.x]
# 리포지토리의 ID 및 이름을 의미 
# elasticsearch-6.x는 Elasticsearch 6.x 버전용 리포지토리를 의미함 

name=Elasticsearch repository for 6.x packages
# 리포지토리의 설명
# 사용자가 YUM을 통해 패키지를 관리할 때 참조할 수 있는 이름

baseurl=https://artifacts.elastic.co/packages/6.x/yum
# Elasticsearch 패키지를 다운로드할 수 있는 기본 URL
# YUM은 이 URL을 통해 패키지 목록과 패키지를 찾을 수 있음 

gpgcheck=1
# GPG(GNU Privacy Guard)를 사용하여 패키지의 무결성을 확인할 것인지를 의미함
# 1이라면 무결성을 확인한다는 의미

gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
# Elasticsearch 패키지의 GPG 키가 위치한 URL을 의미 
# 이 키는 패키지가 Elastic에서 제공한 것임을 검증하는 데 사용됨 

enabled=1
# 이 리포지토리를 활성화할 것인지를 의미함
# 1은 활성화 상태임을 의미함

autorefresh=1
# 리포지토리 메타데이터의 자동 갱신 여부를 설정함 
# 1은 자동 갱신을 활성화함을 의미

type=rpm-md
# 리포지토리의 메타데이터 유형을 나타냄
# rpm-md는 RPM 메타데이터 형식을 사용함을 의미함 
```

- 환경설정 파일 (elasticsearch.yml)
```yml
path.data: /var/lib/elasticsearch
# Elasticsearch가 데이터(인덱스 및 샤드)를 저장할 디스크 경로를 지정함
# /var/lib/elasticsearch는 데이터를 저장하기 위한 기본 디렉토리임

path.logs: /var/log/elasticsearch
# Elasticsearch의 로그 파일을 저장할 경로를 지정함
# /var/log/elasticsearch는 로그 파일을 위한 표준 디렉토리임

cluster.name: peter-es
# Elasticsearch 클러스터의 이름을 지정함
# 이 이름은 클러스터 내의 노드들이 서로를 식별하는 데 사용됨, 여기서 peter-es는 클러스터의 이름임

node.name: peter-kafka001
# 현재 Elasticsearch 노드의 이름을 설정함
# 클러스터 내에서 각 노드를 구분하는 데 사용되며, 여기서는 peter-kafka001 가 노드의 이름임 

network.bind_host: 0.0.0.0
# Elasticsearch 서비스가 바인딩할 네트워크 호스트를 지정함
# 0.0.0.0은 모든 네트워크 인터페이스에서 Elasticsearch가 접근 가능하도록 하는 것을 의미함

http.port: 9200
# Elasticsearch HTTP 서비스를 위한 포트 번호를 지정함, default 는 9200
# 이 포트를 통해 RESTful API와의 통신이 이루어짐

transport.tcp.port:9300
# 클러스터 내 노드 간 통신을 위한 TCP 포트를 설정함, default 는 9300
# 클러스터 내 노드들이 서로 통신하는 데 사용됨 
```

## 키바나를 이용해 엘라스틱서치에 저장된 데이터 확인

- 엘라스틱서치에 저장된 데이터를 키바나를 이용해 분석할 수 있음 
- 키바나와 엘라스틱서치
  - 엘라스틱서치는 분산형 검색 및 분석 엔진으로, 대량의 데이터를 신속하게 저장하고, 검색하고, 분석할 수 있도록 설계되었음. JSON 형식의 문서로 데이터를 처리하며, 복잡한 검색 쿼리를 지원함 
  - 키바나는 엘라스틱서치의 데이터를 시각화하고 탐색하는 데 사용되는 웹 기반 인터페이스임. 키바나를 사용하면 엘라스틱서치에 저장된 데이터를 대시보드, 그래프, 차트 등의 형태로 시각화할 수 있으며, 데이터 탐색 및 실시간 분석이 가능함
  - 엘라스틱서치가 데이터의 저장 및 검색 엔진이라면, 키바나는 이를 사용자가 손쉽게 확인할 수 있는 도구임. 이를 조합하여 사용자는 로그 분석, 성능 모니터링, 데이터 탐색 및 시각화 작업 등을 손쉽게 할 수 있음 
- 키바나 저장소 등록 위한 kibana.repo 파일 
```repo
[kibana-6.x]
# 리포지토리의 ID
# kibana-6.x는 Kibana 6.x 버전용 리포지토리를 의미함 

name=Kibana repository for 6.x packages
# 리포지토리의 이름
# 사용자가 패키지 매니저를 사용하여 Kibana 패키지를 관리할 때 참조할 수 있는 이름

baseurl=https://artifacts.elastic.co/packages/6.x/yum
# Kibana 패키지를 다운로드할 수 있는 기본 URL
# YUM은 이 URL을 통해 Kibana 패키지 목록과 패키지를 찾을 수 있음 

gpgcheck=1
# GPG(GNU Privacy Guard)를 사용하여 패키지의 무결성을 확인할 것인지를 의미함
# 1이라면 무결성을 확인한다는 의미

gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
# Elasticsearch 패키지의 GPG 키가 위치한 URL을 의미 
# 이 키는 패키지가 Elastic에서 제공한 것임을 검증하는 데 사용됨 

eabled=1
# 이 리포지토리를 활성화할 것인지를 의미함
# 1은 활성화 상태임을 의미함

autorefresh=1
# 리포지토리 메타데이터의 자동 갱신 여부를 설정함 
# 1은 자동 갱신을 활성화함을 의미

type=rpm-md
# 리포지토리의 메타데이터 유형을 나타냄
# rpm-md는 RPM 메타데이터 형식을 사용함을 의미함 
```

- 키바나의 설정 파일 (kibana.yml)
```yml
server.host: "0.0.0.0"
# Kibana 서버가 네트워크 상에서 접근 가능한 호스트 주소를 지정
# "0.0.0.0"은 모든 네트워크 인터페이스에서 Kibana에 접근할 수 있음을 의미

elasticsearch.url: "http://peter-kafka001:9200"
# Kibana가 연결할 Elasticsearch 클러스터의 URL을 지정
# Kibana가 데이터를 검색하고 저장하기 위해 연결하는 Elasticsearch 서버의 주소와 포트 번호를 의미 
```
