### ISSUE TITLE
[01-05] Ansible 테크닉

### ISSUE THREAD

**Issue by steammando** [dev-writeup-2024/january#27]
요새 회사에서 Kubespray라는 kubernetes를 설치 및 배포할 수 있게 해주는 툴을 분석해서 최적화하고 있다.
배포하는데에 시간이 너무 오래걸려서(4개 하이퍼바이저에 배포하는데 40분정도) 쓸모 없는 단계는 제거하고 캐싱할 수 있는건 캐싱하고 해볼 수 있는건 다 해보려하는데 이 kubespray를 구성하고 있는 툴이 Ansible이다.

이 ansible을 사용하면서 메모장에 정리한 꿀팁들을 한 번 모아보려 한다.

## Ansible이란

ansible을 모를 수도 있는 분을 위해서 간략하게 설명하자면
Python으로 개발된 IaC 툴이다. AWS 등의 퍼블릭 클라우드 인프라를 코드로 관리하는 테라폼과는 조금 다르게 서버 설정 등 shell script로 여러 서버에 밀어넣는 conf를 관리하는데에 도움을 주는 툴이다.

inventory에 관리하고 싶은 대상 hostname을 작성하면 해당 host에만 배포해준다.
그리고 서버에 밀어넣고 싶은 Task 목록을 작성하는 것이 playbook이다.

agent를 따로 설치하지 않고도 대상 host에 멱등성을 보장하는 task를 실행해주기 때문에 아주 좋은 툴이다.

----------------

### Inline Logging
```
- name: dump all
  hosts: all
  tasks:
    - name: Print some debug information
      vars:
        msg: |
          Module Variables ("vars"):
          --------------------------------
          {{ vars | to_nice_json }}
          ================================

          Environment Variables ("environment"):
          --------------------------------
          {{ environment | to_nice_json }}
          ================================

          Group Variables ("groups"):
          --------------------------------
          {{ groups | to_nice_json }}
          ================================

          Host Variables ("hostvars"):
          --------------------------------
          {{ hostvars | to_nice_json }}
          ================================
      debug:
        msg: "{{ msg.split('\n') }}"tags: debug_info
```
위 같은 내용을 playbook에 추가하면 로그를 남길 수 있다.
to_nice_json은 json beautifier인데 난 딱히 쓰진 않는다.

### ansible-lint 
이건 필수인데 ansible 코드를 대상으로 lint를 돌릴 수 있다.
다른 lint tool과 동일하게 룰설정이 가능하다.

### Ansible Debugger
```
- hosts: all
  debugger: on_failed
  gather_facts: no
  tasks:
    # 테스트용 강제로 실패하는 fail task 사용
    - fail:
```

### 폴더 정리
일단 ansible에서 사용하는 폴더는 상당히 다양하다.
default, meta,task, vars, template 등등이 있는데 용도에 맞게 잘 정리되어야 한다.

특히 default와 vars는 priority 문제가 있기 때문에 실제로 사용할 값은 vars에 적어주는게 좋다.

default는 lower priority variables기 때문에 vars 아래에 동일한 항목이 있다면 vars 의 값으로 덮어씌워진다.

meta의 경우 role 간의 dependencies가 작성된 곳인데 role은 default main.yml에 작성된 내용을 주로 참고하는 것 같다.

### host os version
host의 os version을 가져오기 위해서는 gather facts가 true여야만 가져올 수 있다.
```
- name: Set ansible host os version
  set_facts:
    host_os_version: "{{ hostvars[inventory_hostname]['ansible_distribution_major_version'] }}'
    host_os: "{{ hostvars[inventory_hostname]['ansible_distribution'] }}"
  tags:
  - nginx
```

### playbook 실행 속도 높이기
pipelining으로 ssh 처리 수 줄이기
